# Generated by Django 6.0.7 on 2026-07-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresscorrection',
            options={},
        ),
        migrations.RemoveField(
            model_name='addresscorrection',
            name='corrigido_manualmente',
        ),
        migrations.AddField(
            model_name='addresscorrection',
            name='origem',
            field=models.CharField(default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='addresscorrection',
            name='score_similaridade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addresscorrection',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='addresscorrection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='addresscorrection',
            name='logradouro_original',
            field=models.TextField(),
        ),
    ]
