# Generated by Django 6.0.7 on 2026-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_addresscorrection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscorrection',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='addresscorrection',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
    ]
