# Generated by Django 6.0.7 on 2026-08-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_add_correctionaudit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='correctionaudit',
            name='analytics_correc_corre_123456_idx',
        ),
        migrations.RemoveIndex(
            model_name='correctionaudit',
            name='analytics_correc_logr_123456_idx',
        ),
    ]
