# Generated by Django 6.0.7 on 2026-08-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_correctionaudit_analytics_correc_corre_123456_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscorrection',
            name='logradouro_limpo',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
